language: node_js

node_js:
  - 12.10

addons:
  chrome: stable

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

before_install:
  - npm install -g @lhci/cli@0.8.x

install:
  - npm run install:client
  - npm ci

jobs:
  include:
    - stage: test
      name: "Lighthouse"
      script:
        - npm run build:client
        - lhci autorun --config=./client/lighthouserc.js
    - stage: test
      name: "Cypress component tests"
      script: npm run test:cypress:component:ci
    - stage: test
      name: "Cypress e2e tests"
      script: 
        - npm run build:client
        - npm run test:cypress:ci
    - stage: test
      name: "Unit tests"
      script:
        - echo 'running unit clientt'
        - npm run test:unit:client
    - stage: deploy
      name: "Deployment"
      if: branch IN (other, dev)
      install: skip
      script: echo "Deploying"
      deploy:
        - provider: script
          skip_cleanup: true
          script: echo 'yep deployed cron'
          on:
            condition: type = cron
        - provider: script
          skip_cleanup: true
          script: bash scripts/asdf.sh
          on:
            condition: $TRAVIS_BRANCH = master



