language: node_js

node_js:
  - 12.10

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm run install:client

jobs:
  include:
    - stage: Cypress component testing
      script: npm run test:cypress:component:ci



