language: node_js

node_js:
  - 12.10

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm run install:client
  - npm ci

jobs:
  include:
    - stage: test
      name: "Cypress tests"
      script: npm run test:cypress:component:ci
      if: type = cron
    - stage: test
      name: "Unit tests"
      script:
        - echo 'running unit clientt'
        - npm run test:unit:client
    - stage: deploy
      install: skip
      deploy:
        - provider: script
          script: echo 'yep deployed cron'
          on:
            condition: type IS cron
        - provider: script
          script: echo 'branch asdf only'
          on:
            condition: branch IS asdf
        - provider: script
          script: 
            - echo 'yep deployed no cron'
            - bash scripts/asdf.sh
          on:
            condition: branch IS master



