language: node_js

node_js:
  - 12.10

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm run install:client
  - npm ci

jobs:
  include:
    - stage: test
      script: npm run test:cypress:component:ci
      if: $TRAVIS_EVENT_TYPE == "cron"
    - stage: test
      script:
        - echo 'running unit clientt'
        - npm run test:unit:client
    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: script
          script: echo 'yep deployed cron'
          on:
            condition: $TRAVIS_EVENT_TYPE == "cron"
        - provider: script
          script: echo 'yep deployed no cron'



