language: node_js

node_js:
  - 12.10

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm run install:client
  - npm ci

jobs:
  include:
    - name: Cypress component testing
      script: npm run test:cypress:component:ci
    - name: Component Unit testing
      script: npm run test:unit:client
    - name: DEPLOYINGG
      install: skip
      script: skip
      deploy:
        - provider: script
          script: echo 'yep deployed'



