name: Node CI

on: [push]

env:
  DB_USER: ${{ secrets.MONGODB_DEV_USER }}
  DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 5001
  NODE_ENV: "dev"

jobs:
  build:
    runs-on: [windows-latest]

    strategy:
      matrix:
        node-version: [12.10.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i
          npm run install:client

      - name: Lint source code
        run: |
          npm run lint:backend:windows
          npm run lint:client

      - name: Run unit tests
        run: |
          npm run test:unit:backend
          npm run test:unit:client

      - name: Run UI component tests
        run: |
          npm run test:accessibility:client
          npm run test:snapshot:client

      - name: Build client and run cypress tests
        run: |
          npm run build:client
          npm run test:cypress:ci