name: Node CI

on: [push]

env:
  DB_USER: ${{ secrets.MONGODB_DEV_USER }}
  DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 5001
  NODE_ENV: "dev"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i
          npm run install:client
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm run build:client
          start: npm start
          wait-on: 'http://localhost:5001'