name: Node CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]

    strategy:
      matrix:
        node-version: [12.10.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run install:client
        npm run lint:backend
        npm run lint:client
        npm run test:unit:backend
        npm run test:unit:client
        npm run test:accessibility:client
        npm run test:snapshot:client
      env:
        DB_USER: ${{ secrets.MONGODB_DEV_USER }}
        DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
        CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
        PORT: 5001
        NODE_ENV: "dev"

