name: Node CI

on: [push]

env:
  DB_USER: ${{ secrets.MONGODB_DEV_USER }}
  DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 5001
  NODE_ENV: "dev"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./client
          build: npm run build
          start: npm start