name: Node CI

on: [push]

env:
  DB_USER: ${{ secrets.MONGODB_DEV_USER }}
  DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 5001
  NODE_ENV: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i
          npm run install:client
      
      - name: Lint source code
        run: |
          npm run lint:backend
          npm run lint:client

      - name: Run unit tests
        run: |
          npm run test:unit:backend
          npm run test:unit:client

      - name: Run UI component tests
        run: |
          npm run test:accessibility:client
          npm run test:snapshot:client

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: npm run build:client
          start: npm start
          wait-on: 'http://localhost:5001'
          command: npm run test:cypress:chrome