name: Node CI

on:
  pull_request:
    branches:
      - master
      - dev

env:
  DB_USER: ${{ secrets.MONGODB_DEV_USER }}
  DB_PASS: ${{ secrets.MONGODB_DEV_PASSWORD }}
  CLIENT_ID: ${{ secrets.CLIENT_ID_GITHUB }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_GITHUB }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: 5001
  NODE_ENV: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm i
          npm run install:client

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build:client

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: client/build

      - name: Lint source code
        run: |
          npm run lint:backend
          npm run lint:client

      - name: Run unit tests
        run: |
          npm run test:unit:backend
          npm run test:unit:client

      - name: Run UI component tests
        run: |
          npm run test:accessibility:client
          npm run test:snapshot:client
          npm run test:cypress:component:ci

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
          wait-on: 'http://localhost:5001'
          wait-on-timeout: 120
          command: npm run test:cypress:record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
